// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoList.Data.Context;

#nullable disable

namespace TodoList.Migrations
{
    [DbContext(typeof(ToDoListContext))]
    partial class ToDoListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TodoList.Data.Entities.TodoItem", b =>
                {
                    b.Property<int>("Id_todo_item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_todo_item"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_user")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_todo_item");

                    b.HasIndex("Id_user");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id_todo_item = 1,
                            Description = "enpoints",
                            Id_user = 1,
                            Title = "hacer tp"
                        },
                        new
                        {
                            Id_todo_item = 2,
                            Description = "subir a git",
                            Id_user = 2,
                            Title = "terminar tp"
                        });
                });

            modelBuilder.Entity("TodoList.Data.Entities.User", b =>
                {
                    b.Property<int>("Id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_user"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_user");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id_user = 1,
                            Address = "San Martin 1094",
                            Email = "felidegasperi@gmail.com",
                            Name = "Felipe"
                        },
                        new
                        {
                            Id_user = 2,
                            Address = "Santa Fe 1134",
                            Email = "martin@gmail.com",
                            Name = "Martin"
                        });
                });

            modelBuilder.Entity("TodoList.Data.Entities.TodoItem", b =>
                {
                    b.HasOne("TodoList.Data.Entities.User", "User")
                        .WithMany("TodoItems")
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoList.Data.Entities.User", b =>
                {
                    b.Navigation("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
